name: Ktor CI Pipeline
on:
  push:
    branches:
      - 'feat/MOB-**'
      - 'fix/MOB-**'
      - 'chore/MOB-**'
      - 'main'
      - 'renovate/**'
  workflow_dispatch:
  pull_request:
    branches:
      - 'feat/MOB-**'
      - 'fix/MOB-**'
      - 'chore/MOB-**'
      - 'renovate/**'

jobs:
  BuildKtorApp:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - name: Set up JDK 21
        uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4.4.0
        with:
          distribution: 'adopt'
          java-version: '21'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808 # v4.1.0
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"
        
      - name: Build Ktor application
        run: ./gradlew assemble
        
      - name: Run Linters and Test
        run: ./gradlew check

      - name: Upload Reports
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        with:
          name: Test-Reports
          path: app/build/reports
          retention-days: 1
        if: always()
